### ISSUE TITLE
Update RIT AWS APPLY TERRAFORM formula README

### ISSUE THREAD

**Issue by GuillaumeFalourd** [ZupIT/ritchie-formulas#196]
### What would you like ?

- I would the **RIT AWS APPLY TERRAFORM** formula to have a complete README file explaining what the formula does, with an example of its execution (GIF).

- Formula : https://github.com/ZupIT/ritchie-formulas/tree/master/aws/apply/terraform

### Why is this needed ?

- With the Ritchie Portal (ongoing) those READMEs will be used to share formulas information with the community, and the better they are, the easiest it will be for the community to use them.

### Examples

- https://github.com/ZupIT/ritchie-formulas-demo/tree/master/demo/hello-world
- https://github.com/ZupIT/ritchie-formulas/tree/master/github/publish/repo

**Comment by eduardorcury** [comment]
Hello! I would like to work on this issue :smiley:

**Comment by GuillaumeFalourd** [comment]
It's all yours @eduardorcury , thank you for contributing ! 👍

**Comment by eduardorcury** [comment]
Hello again!
While running the *rit aws apply terraform* command, the first input asked is a selection between the two repositories in the image below. But none of them exist, and I am unable to type my own repository URL. Shouldn't the command ask me to type a new URL, instead of selecting between those two repositories?

![image](https://user-images.githubusercontent.com/60987061/95531328-3dc1c280-09ae-11eb-9972-22ff9437bbad.png)

The *config.json* code for this input is: https://github.com/ZupIT/ritchie-formulas/blob/master/aws/apply/terraform/config.json
```json
    {
      "default": "https://github.com/zupit/iti-stack-core",
      "items": [
        "https://github.com/zupit/iti-stack-core",
        "https://github.com/zupit/iti-stack-tools"
      ],
      "label": "Select your repository URL: ",
      "name": "repository",
      "type": "text",
      "tutorial": "Choose one option"
    }
```

**Comment by GuillaumeFalourd** [comment]
Hi @eduardorcury 

This formula may have been implemented for people with access to those repositories, and probably hasn't been updated since then.

In that case, you can update this input in the config.json file of the formula, asking for any URL:

```
{
      "default": "https://github.com/zupit/iti-stack-core",
      "label": "Type the repository URL: ",
      "name": "repository",
      "type": "text",
      "tutorial": "Inform a github repo URL (ex: https://github.com/zupit/iti-stack-core)"
    }
```

Then, to test the formula locally, you can use the `rit build formula` command as informed here: https://docs.ritchiecli.io/tutorials/formulas/build-a-formula

Feel free to ask any question if needed 👍
